/* MARKET DESK — legacy Safari compatible, provider-backed */
(function(){'use strict';
var CATALOG=[
['NIFTY 50','NIFTY','India','INDEX'],['SENSEX','SENSEX','India','INDEX'],['BANK NIFTY','BANKNIFTY','India','INDEX'],['NIFTY IT','NIFTYIT','India','INDEX'],['NIFTY MIDCAP','MIDCAP','India','INDEX'],
['RELIANCE','RELIANCE','India','STOCK'],['TCS','TCS','India','STOCK'],['HDFC BANK','HDFCBANK','India','STOCK'],['ICICI BANK','ICICIBANK','India','STOCK'],['INFOSYS','INFY','India','STOCK'],
['S&P 500','SPX','USA','INDEX'],['NASDAQ COMPOSITE','IXIC','USA','INDEX'],['NASDAQ 100','NDX','USA','INDEX'],['DOW JONES','DJI','USA','INDEX'],['AAPL','AAPL','USA','STOCK'],['NVIDIA','NVDA','USA','STOCK'],['MICROSOFT','MSFT','USA','STOCK'],['AMAZON','AMZN','USA','STOCK'],['GOOGLE','GOOGL','USA','STOCK'],['META','META','USA','STOCK'],['TESLA','TSLA','USA','STOCK'],
['KOSPI','KOSPI','Korea','INDEX'],['KOSDAQ','KOSDAQ','Korea','INDEX'],['KOSPI 200','K200','Korea','INDEX'],['SAMSUNG ELECTRONICS','005930','Korea','STOCK'],['SK HYNIX','000660','Korea','STOCK'],['HYUNDAI MOTOR','005380','Korea','STOCK'],['LG ENERGY SOLUTION','373220','Korea','STOCK'],
['VOO','VOO','USA','ETF'],['SPY','SPY','USA','ETF'],['QQQ','QQQ','USA','ETF'],['VTI','VTI','USA','ETF']];
var TICKS=[['NIFTY 50','NIFTY'],['SENSEX','SENSEX'],['BANK NIFTY','BANKNIFTY'],['NIFTY IT','NIFTYIT'],['S&P 500','SPX'],['NASDAQ 100','NDX'],['DOW JONES','DJI'],['NVDA','NVDA'],['AAPL','AAPL'],['SAMSUNG','005930'],['GOLD','XAU/USD'],['USD/INR','USD/INR'],['MSFT','MSFT'],['AMZN','AMZN'],['TSLA','TSLA'],['SK HYNIX','000660']];
var WATCH=['NIFTY 50','RELIANCE','TCS','AAPL','NVDA','SAMSUNG ELECTRONICS'];
var TF=localStorage.getItem('md-tf')||'1D',ASSET=localStorage.getItem('md-asset')||'NIFTY 50',theme=localStorage.getItem('md-theme')||'night',LIVE=false,QUOTES={},CHARTS={},CHARTMETA={};
document.body.className=theme==='day'?'day':'night';
function $(id){return document.getElementById(id)}
function fmt(n,d){if(n===undefined||n===null||!isFinite(Number(n)))return'--';d=d===undefined?2:d;return Number(n).toLocaleString('en-IN',{minimumFractionDigits:d,maximumFractionDigits:d})}
function signed(n){return !isFinite(Number(n))?'--':(n>=0?'+':'')+Number(n).toFixed(2)+'%'}
function meta(name){var i;for(i=0;i<CATALOG.length;i++)if(CATALOG[i][0]===name)return CATALOG[i];return[name,name,'Global','ASSET']}
function normalize(d,name){if(!d)return null;var p=Number(d.close||d.price||d.last||d.value);if(!isFinite(p))return null;var pc=Number(d.previous_close||d.previousClose||d.prev_close),ch=Number(d.change),pct=Number(d.percent_change||d.percentChange);if(!isFinite(pct)&&isFinite(ch)&&isFinite(pc)&&pc)pct=ch/pc*100;if(!isFinite(pc)&&isFinite(ch)&&isFinite(pct)&&pct!==-100)pc=p/(1+pct/100);if(!isFinite(pct)&&isFinite(pc)&&pc)pct=(p-pc)/pc*100;return{name:name,price:p,change:isFinite(pct)?pct:0,previous:isFinite(pc)?pc:null,high:Number(d.high),low:Number(d.low),volume:Number(d.volume),open:Number(d.open),currency:d.currency||'USD',local:p,usd:Number(d.usd_price),inr:Number(d.inr_price),updatedAt:d.datetime||null}}
function xhr(url,ok,fail){var x=new XMLHttpRequest();x.onreadystatechange=function(){if(x.readyState===4){if(x.status>=200&&x.status<300){try{ok(JSON.parse(x.responseText))}catch(e){fail(e)}}else fail(x.status)}};x.open('GET',url,true);x.send()}
function setFeed(live){LIVE=!!live;['dataBadge','feedFoot','feedState'].forEach(function(id){var e=$(id);if(e)e.textContent=id==='dataBadge'?(LIVE?'LIVE DATA':'NO LIVE DATA'):(LIVE?'LIVE':'OFFLINE')})}
function fetchQuote(name,cb){var a=meta(name);xhr('/api/market?action=quote&symbol='+encodeURIComponent(a[1]),function(r){if(r.live&&r.data){var q=normalize(r.data,name);if(q){QUOTES[name]=q;setFeed(true);if(cb)cb(q);return}}setFeed(false);if(cb)cb(null)},function(){setFeed(false);if(cb)cb(null)})}
function getQuote(name){return QUOTES[name]||null}
function currencyLine(q){if(!q)return'LOCAL --';return q.currency+' '+fmt(q.local)+'  •  USD '+fmt(q.usd)+'  •  INR ₹'+fmt(q.inr)}
function renderChart(){var q=getQuote(ASSET),a=meta(ASSET);$('chartName').textContent=ASSET;$('chartSymbol').textContent=a[1];if(!q){$('chartPrice').textContent='--';$('chartLocal').textContent='LOCAL --';$('chartUSD').textContent='USD --';$('chartINR').textContent='INR --';$('chartChange').textContent='NO LIVE DATA';$('chartMeta').textContent='Connect market feed';$('volume').textContent='--';$('prevClose').textContent='--';$('high52').textContent='--';$('low52').textContent='--';draw([]);return}
var up=q.change>=0;$('chartPrice').textContent=fmt(q.price);$('chartLocal').textContent=q.currency+' '+fmt(q.local);$('chartUSD').textContent='USD '+fmt(q.usd);$('chartINR').textContent='INR ₹'+fmt(q.inr);$('chartChange').textContent=signed(q.change);$('chartChange').className=up?'up':'down';$('chartMeta').textContent='OHLC '+fmt(q.open)+' / '+fmt(q.high)+' / '+fmt(q.low)+' / '+fmt(q.price);$('volume').textContent=fmt(q.volume,0);$('prevClose').textContent=fmt(q.previous);var m=CHARTMETA[ASSET];$('high52').textContent=m&&m.high52?fmt(m.high52):'--';$('low52').textContent=m&&m.low52?fmt(m.low52):'--';$('chartCurrency').textContent=q.currency+' • USD • INR';$('chartUpdated').textContent='LAST UPDATE '+(q.updatedAt||new Date().toLocaleTimeString());draw(CHARTS[ASSET+'|'+TF]||[])}
function draw(rows){var svg=$('chart'),html='',w=900,h=420,p=42;svg.innerHTML='';if(!rows||!rows.length){html+='<text x="450" y="205" text-anchor="middle" fill="#727b84" font-size="14" font-family="Menlo,Consolas,monospace">WAITING FOR LIVE HISTORICAL DATA</text>';svg.innerHTML=html;return}
var closes=[],i;for(i=0;i<rows.length;i++)closes.push(Number(rows[i].close));var lo=Math.min.apply(null,closes),hi=Math.max.apply(null,closes),range=hi-lo||1,path='',volMax=0;
for(i=0;i<rows.length;i++){var x=p+i*(w-p*2)/(Math.max(1,rows.length-1)),y=p+(hi-closes[i])/range*(h-p*2-48);path+=(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1);volMax=Math.max(volMax,Number(rows[i].volume)||0)}
for(i=0;i<6;i++){var gy=p+i*(h-p*2-48)/5;html+='<line x1="'+p+'" y1="'+gy+'" x2="'+(w-p)+'" y2="'+gy+'" stroke="#20262d"/><text x="6" y="'+(gy+4)+'" fill="#59616a" font-size="10" font-family="Menlo,Consolas,monospace">'+fmt(hi-(hi-lo)*i/5)+'</text>'}
html+='<path d="'+path+'" fill="none" stroke="'+((getQuote(ASSET)||{change:0}).change>=0?'#39ed7b':'#ff555d')+'" stroke-width="2.2"/>';
var base=h-p,volBase=h-18,volTop=h-64;for(i=0;i<rows.length;i++){var vx=p+i*(w-p*2)/(Math.max(1,rows.length-1)),vv=Number(rows[i].volume)||0,vh=volMax?vv/volMax*(volBase-volTop):0;html+='<line x1="'+vx.toFixed(1)+'" y1="'+volBase+'" x2="'+vx.toFixed(1)+'" y2="'+(volBase-vh).toFixed(1)+'" stroke="#3b444d" stroke-width="1" opacity=".65"/>'}
html+='<line x1="'+p+'" y1="'+base+'" x2="'+(w-p)+'" y2="'+base+'" stroke="#30363d"/>';
var first=rows[0].datetime,last=rows[rows.length-1].datetime;html+='<text x="'+p+'" y="410" fill="#59616a" font-size="10" font-family="Menlo,Consolas,monospace">'+labelDate(first)+'</text><text x="'+(w-p)+'" y="410" text-anchor="end" fill="#59616a" font-size="10" font-family="Menlo,Consolas,monospace">'+labelDate(last)+'</text>';
svg.innerHTML=html;bindCrosshair(rows,lo,hi,p,w,h)}
function labelDate(s){if(!s)return'';var d=new Date(String(s).replace(' ','T'));if(!isFinite(d.getTime()))return String(s);if(TF==='1D'||TF==='5D')return d.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});if(TF==='ALL')return d.toLocaleDateString([], {year:'numeric'});return d.toLocaleDateString([], {month:'short',day:'numeric'})}
function bindCrosshair(rows,lo,hi,p,w,h){var svg=$('chart'),line=null,txt=null;function move(ev){var r=svg.getBoundingClientRect(),cx=(ev.touches?ev.touches[0].clientX:ev.clientX)-r.left,ratio=Math.max(0,Math.min(1,cx/r.width)),idx=Math.round(ratio*(rows.length-1)),v=Number(rows[idx].close),x=p+idx*(w-p*2)/Math.max(1,rows.length-1),y=p+(hi-v)/(hi-lo||1)*(h-p*2-48);if(!line){line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('stroke','#87909a');line.setAttribute('stroke-dasharray','3 3');svg.appendChild(line);txt=document.createElementNS('http://www.w3.org/2000/svg','text');txt.setAttribute('fill','#dfe5ea');txt.setAttribute('font-size','11');txt.setAttribute('font-family','Menlo,Consolas,monospace');svg.appendChild(txt)}line.setAttribute('x1',x);line.setAttribute('x2',x);line.setAttribute('y1',p);line.setAttribute('y2',h-18);txt.setAttribute('x',Math.min(w-170,Math.max(p,x+8)));txt.setAttribute('y',24);txt.textContent=labelDate(rows[idx].datetime)+'  '+fmt(v)}
function end(){if(line){svg.removeChild(line);svg.removeChild(txt);line=null;txt=null}}svg.onmousemove=move;svg.onmouseleave=end;svg.ontouchmove=move;svg.ontouchend=end}
function renderTicker(){var h='',i,t,q;for(i=0;i<TICKS.length;i++){t=TICKS[i];q=getQuote(t[0]);h+='<div class="tick"><span>'+t[0]+'</span><b>'+(q?fmt(q.price):'--')+'</b><span class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</span></div>'}$('ticker').innerHTML=h}
function session(m){var d=new Date(),utc=d.getUTCHours()*60+d.getUTCMinutes(),day=d.getUTCDay();if(day===0||day===6)return'CLOSED';if(m==='INDIA')return utc>=225&&utc<600?'OPEN':'CLOSED';if(m==='USA')return utc>=780&&utc<1200?'OPEN':'CLOSED';return utc<360?'OPEN':'CLOSED'}
function renderMarkets(){var groups=[['INDIA',['NIFTY 50','SENSEX','BANK NIFTY','NIFTY IT','NIFTY MIDCAP']],['USA',['S&P 500','NASDAQ COMPOSITE','NASDAQ 100','DOW JONES']],['KRX',['KOSPI','KOSDAQ','KOSPI 200']]],h='',i,j,q,adv=0,dec=0;for(i=0;i<groups.length;i++){h+='<div class="market"><b>'+groups[i][0]+'</b><small>MARKET</small><span class="status">'+session(groups[i][0])+'</span></div>';for(j=0;j<groups[i][1].length;j++){q=getQuote(groups[i][1][j]);if(q){q.change>=0?adv++:dec++}h+='<div class="market"><span class="name">'+groups[i][1][j]+'</span><span class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</span><small>'+(q?fmt(q.price):'--')+'</small></div>'}}$('marketGrid').innerHTML=h;$('heat').innerHTML='<span class="upbox">ADV '+adv+'</span><span class="downbox">DEC '+dec+'</span><span>LIVE '+(adv+dec)+'</span>'}
function renderWatch(){var h='',i,q;for(i=0;i<WATCH.length;i++){q=getQuote(WATCH[i]);h+='<div class="row"><b>'+WATCH[i]+'</b><span>'+(q?fmt(q.price):'--')+'</span><span class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</span></div>'}$('watchlist').innerHTML=h}
function renderGoldFx(){var g=getQuote('GOLD'),fx=getQuote('USD/INR');$('goldFx').innerHTML='<div class="row"><b>GOLD</b><span>'+(g?g.currency+' '+fmt(g.local):'--')+'</span><span class="'+(g?(g.change>=0?'up':'down'):'')+'">'+(g?signed(g.change):'--')+'</span></div><div class="row"><b>USD/INR</b><span>'+(fx?fmt(fx.price):'--')+'</span><span class="'+(fx?(fx.change>=0?'up':'down'):'')+'">'+(fx?signed(fx.change):'--')+'</span></div><div class="row"><b>EUR/USD</b><span>--</span><span>--</span></div><div class="row"><b>USD/KRW</b><span>--</span><span>--</span></div>';$('goldMini').textContent=g?'₹'+fmt(g.inr):'₹--';$('fxMini').textContent=fx?fmt(fx.price):'--'}
function renderCommodities(){var ns=[['SILVER','XAG/USD'],['CRUDE OIL','WTI/USD'],['BRENT','BRENT/USD'],['NATURAL GAS','NATGAS/USD']],h='',i,q;for(i=0;i<ns.length;i++){q=getQuote(ns[i][0]);h+='<div class="row"><b>'+ns[i][0]+'</b><span>'+(q?q.currency+' '+fmt(q.local):'--')+'</span><span class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</span></div>'}$('commodities').innerHTML=h}
function renderTape(){var names=['NIFTY 50','S&P 500','NASDAQ 100','NVDA','AAPL','SAMSUNG ELECTRONICS','SK HYNIX','RELIANCE','TCS','TSLA'],h='',i,q;for(i=0;i<names.length;i++){q=getQuote(names[i]);h+='<div><span>'+names[i]+'</span> '+(q?fmt(q.price):'--')+' <span class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</span></div>'}$('tape').innerHTML=h}
function renderStrip(){var names=['AAPL','NVDA','MSFT','AMZN','GOOGL','META','TSLA','RELIANCE','TCS','HDFCBANK','SAMSUNG ELECTRONICS','SK HYNIX'],h='',i,q;for(i=0;i<names.length;i++){q=getQuote(names[i]);h+='<span class="stripItem"><b>'+names[i]+'</b><em>'+(q?fmt(q.price):'--')+'</em><strong class="'+(q?(q.change>=0?'up':'down'):'')+'">'+(q?signed(q.change):'--')+'</strong></span>'}$('liveStripTrack').innerHTML=h+' '+h}
function render(){renderChart();renderTicker();renderWatch();renderMarkets();renderGoldFx();renderCommodities();renderTape();renderStrip()}
function fetchChart(){var symbol=meta(ASSET)[1];xhr('/api/market?action=chart&symbol='+encodeURIComponent(symbol)+'&tf='+encodeURIComponent(TF),function(r){if(r.live&&r.data&&r.data.values){var vals=r.data.values.slice().reverse(),rows=[],i,v;for(i=0;i<vals.length;i++){v=vals[i];if(isFinite(Number(v.close)))rows.push({datetime:v.datetime,open:Number(v.open),high:Number(v.high),low:Number(v.low),close:Number(v.close),volume:Number(v.volume)||0})}if(rows.length){CHARTS[ASSET+'|'+TF]=rows;var highs=[],lows=[];for(i=0;i<rows.length;i++){highs.push(rows[i].high);lows.push(rows[i].low)}var start=rows.length>260?rows.slice(rows.length-260):rows;var hi=-Infinity,lo=Infinity;for(i=0;i<start.length;i++){hi=Math.max(hi,start[i].high);lo=Math.min(lo,start[i].low)}CHARTMETA[ASSET]={high52:hi,low52:lo};setFeed(true);renderChart()}}},function(){setFeed(false);renderChart()})}
function symbolToName(symbol){var i;for(i=0;i<CATALOG.length;i++)if(CATALOG[i][1]===symbol)return CATALOG[i][0];for(i=0;i<TICKS.length;i++)if(TICKS[i][1]===symbol)return TICKS[i][0];return null}
function fetchAll(){var symbols=[],i,seen={};for(i=0;i<TICKS.length;i++)symbols.push(TICKS[i][1]);for(i=0;i<WATCH.length;i++)symbols.push(meta(WATCH[i])[1]);symbols.push(meta(ASSET)[1]);symbols.push('XAG/USD','WTI/USD','BRENT/USD','NATGAS/USD');for(i=0;i<symbols.length;i++)if(!seen[symbols[i]]){seen[symbols[i]]=1;(function(symbol){xhr('/api/market?action=quote&symbol='+encodeURIComponent(symbol),function(r){if(r.live&&r.data){var n=symbolToName(symbol);if(!n){if(symbol==='XAG/USD')n='SILVER';else if(symbol==='WTI/USD')n='CRUDE OIL';else if(symbol==='BRENT/USD')n='BRENT';else if(symbol==='NATGAS/USD')n='NATURAL GAS'}if(n){var q=normalize(r.data,n);if(q)QUOTES[n]=q;setFeed(true)}}},function(){})})(symbols[i])}setTimeout(render,1200)}
function updateClock(){var d=new Date();$('localTime').textContent=d.toLocaleTimeString();$('localDate').textContent=d.toLocaleDateString();$('location').textContent=localStorage.getItem('md-city')||'Jaipur'}
function searchLocal(v){v=v.toLowerCase();var h='',i,a;for(i=0;i<CATALOG.length;i++){a=CATALOG[i];if(!v||a.join(' ').toLowerCase().indexOf(v)>=0)h+='<div class="result" data-name="'+a[0]+'"><b>'+a[0]+' <span>'+a[1]+'</span></b><span>'+a[2]+' • '+a[3]+'</span></div>'}$('searchResults').innerHTML=h}
function globalSearch(v){if(!v){searchLocal('');return}xhr('/api/market?action=search&q='+encodeURIComponent(v),function(r){if(r.live&&r.data&&r.data.length){var h='',i,a;for(i=0;i<Math.min(r.data.length,30);i++){a=r.data[i];h+='<div class="result remote" data-symbol="'+(a.symbol||'')+'" data-name="'+(a.instrument_name||a.name||a.symbol||'')+'"><b>'+(a.instrument_name||a.name||a.symbol||'')+' <span>'+(a.symbol||'')+'</span></b><span>'+(a.exchange||'GLOBAL')+' • '+(a.type||'ASSET')+'</span></div>'}$('searchResults').innerHTML=h}else searchLocal(v)},function(){searchLocal(v)})}
$('searchBtn').onclick=function(){$('searchModal').className='modal';$('assetSearch').focus();searchLocal('')};$('closeSearch').onclick=function(){$('searchModal').className='modal hidden'};$('assetSearch').onkeyup=function(){globalSearch(this.value)};$('searchResults').onclick=function(e){var n=e.target;while(n&&n!==$('searchResults')&&n.className.indexOf('result')<0)n=n.parentNode;if(n&&n!==$('searchResults')){var name=n.getAttribute('data-name'),sym=n.getAttribute('data-symbol');if(sym)CATALOG.push([name,sym,'Global','ASSET']);ASSET=name;localStorage.setItem('md-asset',ASSET);$('searchModal').className='modal hidden';fetchQuote(ASSET,function(){fetchChart();render()})}};
$('pinBtn').onclick=function(){localStorage.setItem('md-asset',ASSET);this.textContent='✓ PINNED '+ASSET};
$('timeframes').onclick=function(e){if(e.target.tagName==='BUTTON'){TF=e.target.getAttribute('data-tf');localStorage.setItem('md-tf',TF);var b=document.querySelectorAll('#timeframes button'),i;for(i=0;i<b.length;i++)b[i].className=b[i]===e.target?'active':'';fetchChart()}};
$('themeBtn').onclick=function(){theme=theme==='night'?'day':'night';document.body.className=theme;localStorage.setItem('md-theme',theme);$('themeSelect').value=theme};
$('settingsBtn').onclick=function(){$('settings').className='drawer';$('themeSelect').value=theme};$('closeSettings').onclick=function(){$('settings').className='drawer hidden'};$('themeSelect').onchange=function(){theme=this.value;document.body.className=theme;localStorage.setItem('md-theme',theme)};$('animSelect').onchange=function(){localStorage.setItem('md-anim',this.value)};$('resetBtn').onclick=function(){localStorage.removeItem('md-asset');localStorage.removeItem('md-tf');localStorage.removeItem('md-theme');location.reload()};
updateClock();render();fetchAll();fetchChart();setInterval(updateClock,1000);setInterval(fetchAll,30000);setInterval(fetchChart,30000);
})();