/* MARKET DESK — Stage 1 static command centre. Intentionally no fabricated live feed. */
(function(){
'use strict';
var CATALOG=[
['NIFTY 50','NIFTY','India','INDEX'],['SENSEX','SENSEX','India','INDEX'],['BANK NIFTY','BANKNIFTY','India','INDEX'],['NIFTY IT','NIFTYIT','India','INDEX'],['NIFTY MIDCAP','MIDCAP','India','INDEX'],
['RELIANCE','RELIANCE','India','STOCK'],['TCS','TCS','India','STOCK'],['HDFC BANK','HDFCBANK','India','STOCK'],['ICICI BANK','ICICIBANK','India','STOCK'],['INFOSYS','INFY','India','STOCK'],
['S&P 500','SPX','USA','INDEX'],['NASDAQ COMPOSITE','IXIC','USA','INDEX'],['NASDAQ 100','NDX','USA','INDEX'],['DOW JONES','DJI','USA','INDEX'],
['AAPL','AAPL','USA','STOCK'],['NVIDIA','NVDA','USA','STOCK'],['MICROSOFT','MSFT','USA','STOCK'],['AMAZON','AMZN','USA','STOCK'],['GOOGLE','GOOGL','USA','STOCK'],['META','META','USA','STOCK'],['TESLA','TSLA','USA','STOCK'],
['KOSPI','KOSPI','Korea','INDEX'],['KOSDAQ','KOSDAQ','Korea','INDEX'],['KOSPI 200','K200','Korea','INDEX'],['SAMSUNG ELECTRONICS','005930','Korea','STOCK'],['SK HYNIX','000660','Korea','STOCK'],['HYUNDAI MOTOR','005380','Korea','STOCK'],['LG ENERGY SOLUTION','373220','Korea','STOCK'],
['VOO','VOO','USA','ETF'],['SPY','SPY','USA','ETF'],['QQQ','QQQ','USA','ETF'],['VTI','VTI','USA','ETF']
];
var TICKS=[['NIFTY 50',25140.8,0.64],['SENSEX',82310.2,-0.22],['BANK NIFTY',57140.1,0.91],['NIFTY IT',40320.4,-0.37],['S&P 500',5748.1,0.31],['NASDAQ 100',21120.7,0.58],['DOW JONES',42310.2,-0.14],['NVDA',181.42,1.28],['AAPL',255.14,-0.18],['SAMSUNG',93200,-0.43],['GOLD',117450,0.44],['USD/INR',88.71,0.12]];
var WATCH=['NIFTY 50','RELIANCE','TCS','AAPL','NVDA','SAMSUNG ELECTRONICS'];
var TF='1D', ASSET='NIFTY 50', theme=localStorage.getItem('md-theme')||'night';
document.body.className=theme==='day'?'day':'night';
function $(id){return document.getElementById(id)}
function fmt(n,d){return Number(n).toLocaleString('en-IN',{minimumFractionDigits:d||2,maximumFractionDigits:d||2})}
function signed(n){return (n>=0?'+':'')+n.toFixed(2)+'%'}
function seed(s){var x=0,i;for(i=0;i<s.length;i++)x=((x<<5)-x)+s.charCodeAt(i),x|=0;return Math.abs(x)+1}
function series(symbol,tf){var n=tf==='1D'?90:tf==='1W'?84:tf==='1M'?70:tf==='3M'?70:tf==='6M'?75:tf==='1Y'?80:90,x=seed(symbol+tf),a=[],v=100,i;for(i=0;i<n;i++){x=(x*1664525+1013904223)%4294967296;var r=((x/4294967296)-.5)*1.9;v=Math.max(60,v+r+(i/n)*7);a.push(v)}return a}
function asset(){var i;for(i=0;i<CATALOG.length;i++)if(CATALOG[i][0]===ASSET)return CATALOG[i];return CATALOG[0]}
function quote(name){var i;for(i=0;i<TICKS.length;i++)if(TICKS[i][0]===name)return TICKS[i];var s=seed(name);return[name,50+(s%9000)/10,((s%240)-120)/100]}
function draw(){var s=series(asset()[1],TF),w=900,h=420,p=34,lo=Math.min.apply(null,s),hi=Math.max.apply(null,s),path='',i;for(i=0;i<s.length;i++){var x=p+i*(w-p*2)/(s.length-1),y=h-p-(s[i]-lo)/(hi-lo||1)*(h-p*2);path+=(i?'L':'M')+x.toFixed(1)+','+y.toFixed(1)}var q=quote(ASSET),up=q[2]>=0,stroke=up?'#39ed7b':'#ff555d',html='',g;for(i=1;i<6;i++){var gy=p+i*(h-p*2)/6;html+='<line x1="'+p+'" y1="'+gy+'" x2="'+(w-p)+'" y2="'+gy+'" stroke="#20262d" stroke-width="1"/>'}html+='<path d="'+path+'" fill="none" stroke="'+stroke+'" stroke-width="2.2"/>';html+='<line x1="'+p+'" y1="'+(h-p)+'" x2="'+(w-p)+'" y2="'+(h-p)+'" stroke="#30363d"/>';for(i=0;i<5;i++){g=p+i*(w-p*2)/4;html+='<text x="'+g+'" y="'+(h-7)+'" fill="#69737d" font-size="9" font-family="monospace">'+['09:30','11:00','13:00','15:00','16:00'][i]+'</text>'} $('chart').innerHTML=html}
function render(){var q=quote(ASSET),up=q[2]>=0; $('chartName').textContent=ASSET;$('chartSymbol').textContent=asset()[1];$('chartPrice').textContent=fmt(q[1]);$('chartChange').textContent=signed(q[2]);$('chartChange').className=up?'up':'down';$('chartMeta').textContent='OHLC '+fmt(q[1]*.995)+' / '+fmt(q[1]*1.012)+' / '+fmt(q[1]*.988)+' / '+fmt(q[1]);$('volume').textContent=fmt(seed(ASSET)%9000000+1000000,0);$('prevClose').textContent=fmt(q[1]/(1+q[2]/100));$('high52').textContent=fmt(q[1]*1.16);$('low52').textContent=fmt(q[1]*.78);$('chartUpdated').textContent='LAST UPDATE '+new Date().toLocaleTimeString();draw();renderWatch();renderTicker();renderMarkets();renderGoldFx();renderCommodities();renderTape()}
function renderTicker(){var h='',i,t;for(i=0;i<TICKS.length;i++){t=TICKS[i];h+='<div class="tick"><span>'+t[0]+'</span><b>'+fmt(t[1])+'</b><span class="'+(t[2]>=0?'up':'down')+'">'+signed(t[2])+'</span></div>'}$('ticker').innerHTML=h}
function renderMarkets(){var groups=[['INDIA',['NIFTY 50','SENSEX','BANK NIFTY','NIFTY IT','NIFTY MIDCAP']],['USA',['S&P 500','NASDAQ COMPOSITE','NASDAQ 100','DOW JONES']],['KOREA',['KOSPI','KOSDAQ','KOSPI 200']]],h='',i,j,q,open;for(i=0;i<groups.length;i++){h+='<div class="market"><b>'+groups[i][0]+'</b><small>MARKET</small><span class="status">'+session(groups[i][0])+'</span></div>';for(j=0;j<groups[i][1].length;j++){q=quote(groups[i][1][j]);h+='<div class="market"><span class="name">'+groups[i][1][j]+'</span><span class="'+(q[2]>=0?'up':'down')+'">'+signed(q[2])+'</span><small>'+fmt(q[1])+'</small></div>'}}$('marketGrid').innerHTML=h;$('heat').innerHTML='<span class="upbox">ADV 8</span><span class="downbox">DEC 4</span><span>UNCH 2</span>'}
function session(m){var d=new Date(),day=d.getUTCDay();if(day===0||day===6)return 'CLOSED';var mins=d.getUTCHours()*60+d.getUTCMinutes();if(m==='INDIA')return mins>=225&&mins<600?'OPEN':'CLOSED';if(m==='USA')return mins>=810&&mins<1200?'OPEN':'CLOSED';return mins>=0&&mins<360?'OPEN':'CLOSED'}
function renderWatch(){var h='',i,q;for(i=0;i<WATCH.length;i++){q=quote(WATCH[i]);h+='<div class="row"><b>'+WATCH[i]+'</b><span>'+fmt(q[1])+'</span><span class="'+(q[2]>=0?'up':'down')+'">'+signed(q[2])+'</span></div>'}$('watchlist').innerHTML=h}
function renderGoldFx(){$('goldFx').innerHTML='<div class="row"><b>GOLD ₹/10g</b><span>₹1,17,450</span><span class="up">+0.44%</span></div><div class="row"><b>USD/INR</b><span>88.71</span><span class="up">+0.12%</span></div><div class="row"><b>EUR/USD</b><span>1.173</span><span class="down">-0.08%</span></div><div class="row"><b>USD/JPY</b><span>147.2</span><span class="up">+0.11%</span></div>'; $('goldMini').textContent='₹1,17,450';$('fxMini').textContent='88.71'}
function renderCommodities(){$('commodities').innerHTML='<div class="row"><b>SILVER</b><span>1,460</span><span class="up">+0.51%</span></div><div class="row"><b>CRUDE OIL</b><span>70.8</span><span class="down">-0.36%</span></div><div class="row"><b>BRENT</b><span>74.9</span><span class="down">-0.21%</span></div><div class="row"><b>NATURAL GAS</b><span>3.41</span><span class="up">+0.72%</span></div>'}
function renderTape(){$('tape').innerHTML='<div><span class="up">NIFTY 50</span> holding positive territory • DEMO</div><div><span class="up">NASDAQ 100</span> higher in sample feed</div><div><span class="down">KOSPI</span> softer in sample feed</div><div><span class="up">GOLD</span> ₹1,17,450 / 10g • DEMO</div><div><span class="up">USD/INR</span> 88.71 • DEMO</div>'}
function updateClock(){var d=new Date();$('localTime').textContent=d.toLocaleTimeString();$('localDate').textContent=d.toLocaleDateString();$('location').textContent='LOCAL';try{navigator.geolocation.getCurrentPosition(function(){ $('location').textContent='LOCATION ENABLED';},function(){ $('location').textContent='LOCAL';},{maximumAge:300000,timeout:3000});}catch(e){}}
function openSearch(){$('searchModal').className='modal';$('assetSearch').focus();search('')}
function search(v){v=v.toLowerCase();var h='',i,a;for(i=0;i<CATALOG.length;i++){a=CATALOG[i];if(!v||a.join(' ').toLowerCase().indexOf(v)>=0)h+='<div class="result" data-name="'+a[0]+'"><b>'+a[0]+' <span>'+a[1]+'</span></b><span>'+a[2]+' • '+a[3]+'</span></div>'}$('searchResults').innerHTML=h}
$('searchBtn').onclick=openSearch;$('closeSearch').onclick=function(){$('searchModal').className='modal hidden'};$('assetSearch').onkeyup=function(){search(this.value)};$('searchResults').onclick=function(e){var n=e.target.closest?e.target.closest('.result'):null;if(n){ASSET=n.getAttribute('data-name');localStorage.setItem('md-asset',ASSET);$('searchModal').className='modal hidden';render()}}
$('pinBtn').onclick=function(){localStorage.setItem('md-asset',ASSET);this.textContent='✓ PINNED '+ASSET};$('timeframes').onclick=function(e){if(e.target.tagName==='BUTTON'){TF=e.target.getAttribute('data-tf');localStorage.setItem('md-tf',TF);var b=document.querySelectorAll('#timeframes button'),i;for(i=0;i<b.length;i++)b[i].className=b[i]===e.target?'active':'';draw()}}
$('themeBtn').onclick=function(){theme=theme==='night'?'day':'night';document.body.className=theme;localStorage.setItem('md-theme',theme);$('themeSelect').value=theme};$('settingsBtn').onclick=function(){$('settings').className='drawer';$('themeSelect').value=theme};$('closeSettings').onclick=function(){$('settings').className='drawer hidden'};$('themeSelect').onchange=function(){theme=this.value;document.body.className=theme;localStorage.setItem('md-theme',theme)};$('animSelect').onchange=function(){localStorage.setItem('md-anim',this.value)};$('resetBtn').onclick=function(){localStorage.removeItem('md-asset');localStorage.removeItem('md-tf');localStorage.removeItem('md-theme');location.reload()}
ASSET=localStorage.getItem('md-asset')||'NIFTY 50';TF=localStorage.getItem('md-tf')||'1D';var bs=document.querySelectorAll('#timeframes button'),i;for(i=0;i<bs.length;i++)if(bs[i].getAttribute('data-tf')===TF)bs[i].className='active';updateClock();render();setInterval(updateClock,1000);setInterval(function(){render()},30000);
})();